# Generated by Django 4.1.2 on 2022-11-10 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(default='')),
                ('min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_date', models.DateTimeField(blank=True, null=True)),
                ('max_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('key', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Form Section',
                'verbose_name_plural': 'Form Sections',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(default='')),
                ('code', models.CharField(default='', max_length=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.form')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(default='')),
                ('code', models.CharField(default='', max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='Services.servicetype')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ServiceApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_number', models.CharField(blank=True, max_length=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.servicecategory')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='FormSectionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('default', models.CharField(blank=True, max_length=50, null=True)),
                ('readonly', models.BooleanField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Services.formfield')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Services.formsection')),
            ],
            options={
                'verbose_name': 'Form Section Field',
                'verbose_name_plural': 'Form Section Fields',
                'ordering': ('index',),
            },
        ),
        migrations.AddField(
            model_name='formsection',
            name='fields',
            field=models.ManyToManyField(through='Services.FormSectionField', to='Services.formfield'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='Services.form'),
        ),
    ]
