# Generated by Django 4.1.2 on 2022-11-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='ServiceOrder',
        ),
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'verbose_name': 'Service Order', 'verbose_name_plural': 'Service Orders'},
        ),
    ]
