# Generated by Django 4.1.2 on 2022-11-16 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.form'),
        ),
    ]
