# Generated by Django 4.1.2 on 2022-11-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_bill_application_submission'),
        ('Services', '0009_remove_serviceapplications_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceApplications',
        ),
    ]
