# Generated by Django 4.1.2 on 2022-11-20 13:55

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0016_alter_service_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='service_type', chained_model_field='type', null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.servicecategory'),
        ),
    ]
