# Generated by Django 4.1.2 on 2022-11-21 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0018_alter_service_consultant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.consultant'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.servicecategory'),
        ),
    ]
