# Generated by Django 3.2 on 2022-11-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0020_rename_service_category_service_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraserviceinfo',
            name='price',
        ),
        migrations.AddField(
            model_name='extraserviceinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extraserviceinfo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
