# Generated by Django 3.2 on 2022-12-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0022_service_serviceinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pay',
            field=models.CharField(blank=True, choices=[('Pay During Visit', 'Pay during Visit')], max_length=200, null=True),
        ),
    ]
