# Generated by Django 3.2 on 2023-01-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0024_auto_20221219_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
