# Generated by Django 3.2 on 2023-01-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0026_service_cleaning_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date_string',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
