# Generated by Django 3.2 on 2023-01-09 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0028_auto_20230109_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='date_string',
            new_name='service_date_string',
        ),
    ]
