# Generated by Django 3.2 on 2023-01-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0029_rename_date_string_service_service_date_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_date_string',
            field=models.DateField(blank=True, null=True),
        ),
    ]
