# Generated by Django 4.1.2 on 2022-11-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_accounts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
